# Generated by Django 3.2.6 on 2021-08-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210829_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ccontact_name',
            new_name='contact_name',
        ),
    ]
